[workspace]
members = [
	"Element/Echo",
	"Element/Maintain",
	"Element/Maintain/Dependency/CodeEditorLand/Dependency/Queue",
	"Element/Mountain",
	"Element/Rest",
	"Element/River",
	"Element/Sun",
]
resolver = "2"
exclude = [
	"Dependency/Microsoft/Dependency/Editor/cli",
	"Dependency/Microsoft/Dependency/Editor/build/win32",
]

[workspace.package]
authors = ["Sourceâ€ğŸ–‹ï¸â€Openâ€ğŸ‘ğŸ» <Source/Open@Editor.Land>"]
documentation = "HTTPS://Documentation.Editor.Land"
edition = "2021"
homepage = "HTTPS://Editor.Land/"
license-file = "LICENSE"
publish = false
readme = "README.md"
repository = "https://github.com/CodeEditorLand/Land"

[workspace.metadata]
# TODO: Fill in the projects metadata (which binary is what)

[workspace.dependencies]
prun = { version = "*" }
